In [30]:
import pandas as pd

In [31]:
data = pd.read_excel("employee.xlsx")

In [32]:
data.head(2)

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
1       2    1107     Officer         IT  30.0   80000.0

## Dealing Rows

In [14]:
data = pd.read_excel("employee.xlsx",index_col="Serial")

In [16]:
data[2:5]

        Emp_ID Designation Department   Age    Salary
Serial
3         1203     Officer         HR  28.0       NaN
4         1005     Manager         HR  45.0  120000.0
5         2123  Office Boy   Accounts  27.0   45000.0

In [22]:
data[[2:5,1:]]

SyntaxError: invalid syntax (197896538.py, line 1)

### iloc or loc

In [ ]:
iloc  ---> integher loc

In [26]:
    r     s:e col  s :e
data.iloc[2:5,     1:4]

       Designation Department   Age
Serial
3          Officer         HR  28.0
4          Manager         HR  45.0
5       Office Boy   Accounts  27.0

In [35]:
data.iloc[1:11, 3:4]

    Department
1           IT
2           HR
3           HR
4     Accounts
5          NaN
6     Accounts
7           IT
8           IT
9   Production
10  Production

In [40]:
# location
data.loc[0:6,"Emp_ID":"Department"]

   Emp_ID Designation Department
0    1101     Manager   Accounts
1    1107     Officer         IT
2    1203     Officer         HR
3    1005     Manager         HR
4    2123  Office Boy   Accounts
5    2451  Accountant        NaN
6    1111  Accountant   Accounts

In [44]:
data.loc[2:7,"Emp_ID":]

   Emp_ID Designation Department   Age    Salary
2    1203     Officer         HR  28.0       NaN
3    1005     Manager         HR  45.0  120000.0
4    2123  Office Boy   Accounts  27.0   45000.0
5    2451  Accountant        NaN  34.0  100000.0
6    1111  Accountant   Accounts   NaN  110000.0
7    1001     Officer         IT  25.0   75000.0

In [50]:
data[data.Designation=="Manager"]

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
3       4    1005     Manager         HR  45.0  120000.0
8       9    1234     Manager         IT  23.0       NaN

In [51]:
data.Designation[data.Designation=="Manager"]

0    Manager
3    Manager
8    Manager
Name: Designation, dtype: object

In [54]:
data[data.Salary<=100000.0]

    Serial  Emp_ID Designation  Department   Age    Salary
1        2    1107     Officer          IT  30.0   80000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
7        8    1001     Officer          IT  25.0   75000.0
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    2156    Engineer  Production  45.0   89000.0
19      20    6543     Officer  Production  29.0  100000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0

In [56]:
data[data.Age==25]

    Serial  Emp_ID Designation Department   Age    Salary
7        8    1001     Officer         IT  25.0   75000.0
13      14    1098     Officer         IT  25.0  100000.0
15      16    1222     Officer        NaN  25.0       NaN
23      24    1098     Officer         IT  25.0  100000.0

In [63]:
data[data.Designation=="Officer"]["Age"]

1     30.0
2     28.0
7     25.0
10    29.0
13    25.0
14    31.0
15    25.0
19    29.0
23    25.0
Name: Age, dtype: float64

In [64]:
data[data.Designation=="Officer"]["Department"]

1             IT
2             HR
7             IT
10    Production
13            IT
14            IT
15           NaN
19    Production
23            IT
Name: Department, dtype: object

In [68]:
data[(data.Designation=="Officer")& (data.Department=="HR")]

   Serial  Emp_ID Designation Department   Age  Salary
2       3    1203     Officer         HR  28.0     NaN

In [70]:
data.Salary.max()

200000.0

In [72]:
data[data.Salary==200000.0]

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0

In [73]:
data[data.Salary==data.Salary.max()]

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0

In [ ]:
python :   pandas
  or        |
  and       &

In [76]:
data[(data.Department=="IT")  | (data.Age==27)]

    Serial  Emp_ID Designation Department   Age    Salary
1        2    1107     Officer         IT  30.0   80000.0
4        5    2123  Office Boy   Accounts  27.0   45000.0
7        8    1001     Officer         IT  25.0   75000.0
8        9    1234     Manager         IT  23.0       NaN
13      14    1098     Officer         IT  25.0  100000.0
14      15    2912     Officer         IT  31.0   90000.0
17      18    2123  Office Boy   Accounts  27.0   45000.0
23      24    1098     Officer         IT  25.0  100000.0

In [77]:
data["colum_age_salary_multiply"] = data.Age*data.Salary

In [79]:
data[(data.Designation=="Officer")  & (data.Department=="IT")  &  (data.Age==28)]

Empty DataFrame
Columns: [Serial, Emp_ID, Designation, Department, Age, Salary, colum_age_salary_multiply]
Index: []

In [82]:
data[(data.Designation=="Officer")  & (data.Department=="HR")  &  (data.Age==28)]

,Serial,Emp_ID,Designation,Department,Age,Salary,colum_age_salary_multiply
2,3,1203,Officer,HR,28.0,NaN,NaN

In [83]:
data.Designation

0        Manager
1        Officer
2        Officer
3        Manager
4     Office Boy
5     Accountant
6     Accountant
7        Officer
8        Manager
9       Engineer
10       Officer
11    Accountant
12      Engineer
13       Officer
14       Officer
15       Officer
16      Engineer
17    Office Boy
18      Engineer
19       Officer
20    Accountant
21    Accountant
22      Engineer
23       Officer
Name: Designation, dtype: object

### MOvie Data

In [121]:
df=pd.read_csv("movie.csv")
df.head(12)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0
5,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,94.0,Peter Jackson,Elijah Wood,1642758,377845905.0
6,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,94.0,Quentin Tarantino,John Travolta,1826188,107928762.0
7,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,94.0,Steven Spielberg,Liam Neeson,1213505,96898818.0
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,74.0,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0
9,Fight Club,1999,A,139 min,Drama,8.8,66.0,David Fincher,Brad Pitt,1854740,37030102.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,U,178 min,"Action, Adventure, Drama",8.8,92.0,Peter Jackson,Elijah Wood,1661481,315544750.0
11,Forrest Gump,1994,UA,142 min,"Drama, Romance",8.8,82.0,Robert Zemeckis,Tom Hanks,1809221,330252182.0

In [124]:
df.tail(10)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
990,Giù la testa,1971,PG,157 min,"Drama, War, Western",7.6,77.0,Sergio Leone,Rod Steiger,30144,696690.0
991,Kelly's Heroes,1970,GP,144 min,"Adventure, Comedy, War",7.6,50.0,Brian G. Hutton,Clint Eastwood,45338,1378435.0
992,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,65.0,Wolfgang Reitherman,Phil Harris,166409,141843612.0
993,Blowup,1966,A,111 min,"Drama, Mystery, Thriller",7.6,82.0,Michelangelo Antonioni,David Hemmings,56513,NaN
994,A Hard Day's Night,1964,U,87 min,"Comedy, Music, Musical",7.6,96.0,Richard Lester,John Lennon,40351,13780024.0
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

In [129]:
data.sample(3)

,Serial,Emp_ID,Designation,Department,Age,Salary,colum_age_salary_multiply
7,8,1001,Officer,IT,25.0,75000.0,1875000.0
14,15,2912,Officer,IT,31.0,90000.0,2790000.0
1,2,1107,Officer,IT,30.0,80000.0,2400000.0

### unique or nunique